# Generated by Django 5.0.4 on 2024-05-10 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0002_remove_post_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to='site1/static/site1/post_images'),
        ),
    ]
