-- MySQL Script generated by MySQL Workbench
-- Sat Mar 30 20:48:21 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema demo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema demo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `demo` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `demo` ;

-- -----------------------------------------------------
-- Table `demo`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demo`.`user` (
  `ID` INT NOT NULL,
  `Name` VARCHAR(30) NOT NULL,
  `UserName` VARCHAR(45) NULL DEFAULT NULL,
  `Password` VARCHAR(45) NULL DEFAULT NULL,
  `Email` VARCHAR(45) NULL DEFAULT NULL,
  `Birthday` DATETIME NULL DEFAULT NULL,
  `Gender` VARCHAR(5) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `demo`.`tool`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demo`.`tool` (
  `ToolID` VARCHAR(20) NOT NULL,
  `ToolName` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ToolID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `demo`.`use_tool`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demo`.`use_tool` (
  `ID` INT NOT NULL,
  `ToolID` VARCHAR(20) NOT NULL,
  `Number` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ID`, `ToolID`),
  INDEX `useToolID_idx` (`ToolID` ASC) VISIBLE,
  CONSTRAINT `ID_UseTool`
    FOREIGN KEY (`ID`)
    REFERENCES `demo`.`user` (`ID`),
  CONSTRAINT `Tool_UseTool`
    FOREIGN KEY (`ToolID`)
    REFERENCES `demo`.`tool` (`ToolID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `demo`.`calories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demo`.`calories` (
  `caloID` INT NOT NULL,
  `ToolID` VARCHAR(20) NULL DEFAULT NULL,
  `Day` INT NULL DEFAULT NULL,
  `Calo_In` INT NULL DEFAULT NULL,
  `Calo_Out` INT NULL DEFAULT NULL,
  PRIMARY KEY (`caloID`),
  INDEX `Calo_UseTool_idx` (`ToolID` ASC) VISIBLE,
  CONSTRAINT `Calo_UseTool`
    FOREIGN KEY (`ToolID`)
    REFERENCES `demo`.`use_tool` (`ToolID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `demo`.`exercise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demo`.`exercise` (
  `eID` INT NOT NULL,
  `ToolID` VARCHAR(20) NULL DEFAULT NULL,
  `Day` INT NULL DEFAULT NULL,
  `Excercise` LONGTEXT NULL DEFAULT NULL,
  `Time` INT NULL DEFAULT NULL,
  PRIMARY KEY (`eID`),
  INDEX `Exercise_UseTool_idx` (`ToolID` ASC) VISIBLE,
  CONSTRAINT `Exercise_UseTool`
    FOREIGN KEY (`ToolID`)
    REFERENCES `demo`.`use_tool` (`ToolID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `demo`.`food`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demo`.`food` (
  `foodID` INT NOT NULL,
  `ToolID` VARCHAR(20) NULL DEFAULT NULL,
  `foodName` VARCHAR(45) NULL DEFAULT NULL,
  `Instruction` LONGTEXT NULL DEFAULT NULL,
  `Ingredients` LONGTEXT NULL DEFAULT NULL,
  `Calo` INT NULL DEFAULT NULL,
  PRIMARY KEY (`foodID`),
  INDEX `foodID_ToolID_idx` (`ToolID` ASC) VISIBLE,
  CONSTRAINT `Food_UseTool`
    FOREIGN KEY (`ToolID`)
    REFERENCES `demo`.`use_tool` (`ToolID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
